### ISSUE TITLE
"conda install ecl" gives "Value for sha256 cannot be None."

### ISSUE THREAD

**Issue by mattwala** [conda-forge/ecl-feedstock#5]
I tried with the latest miniconda (4/17) and I got the following error after doing "conda install ecl"

    conda._vendor.auxlib.exceptions.ValidationError: Value for sha256 cannot be None.

Indeed, we have

```
$ grep -C3 null ecl-16.1.3-3/info/paths.json
    {
      "_path": "lib/ecl",
      "path_type": "softlink",
      "sha256": null,
      "size_in_bytes": 1904
    },
    {
--
--
    {
      "_path": "lib/ecl-16.1.3/ecl",
      "path_type": "softlink",
      "sha256": null,
      "size_in_bytes": 816
    },
    {
```

This seems to break both on OS X and Linux.

**Comment by isuruf** [comment]
This is an issue with conda-build. https://github.com/conda/conda-build/issues/1934
Downgrading to `ecl-16.1.3-2` might help.

**Comment by isuruf** [comment]
Updating `conda` should fix this.

**Comment by mattwala** [comment]
Yes, it looks like updating conda fixed it.

**Comment by isuruf** [comment]
I pulled the package, so you might not be testing the new package

**Comment by mattwala** [comment]
Woops, you're right.

**Comment by isuruf** [comment]
I've reuploaded the 16.1.3-3 packages. Can you check now?

**Comment by mattwala** [comment]
Yes, the updated conda installed the 16.1.3-3 packages without any issue.

**Comment by isuruf** [comment]
Thanks for checking
